name: recursive_caster
description: A library for simplifying recursive casting for objects.
version: 1.0.0
repository: https://github.com/Calebh101/dart-recursive-caster

environment:
  sdk: ^3.8.1

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
